version: 0.2

phases:
  pre_build:
    commands:
      - cd api
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - sudo apt-get install yarn
  build:
    commands:
      - npm install  
  post_build:
    commands:
      - npm run deploy
artifacts:
  files:
    - '**/*'
  name: myname-$(AWS_REGION) 
