version: 0.2

phases:
  pre_build:
    commands:
      - cd api
  build:
    commands:
      - npm install  
  post_build:
    commands:
      - aws lambda update-function-code --function-name ipa-converter --zip-file file:///./dist/index.zip
artifacts:
  files:
    - '**/*'
  name: myname-$(AWS_REGION) 
