version: 0.2

phases:
  pre_build:
    commands:
      - cd api
  build:
    commands:
      - npm install  
  post_build:
    commands:
      - npm run deploy
artifacts:
  files:
    - '**/*'
  name: myname-$(AWS_REGION) 
