version: 0.2

phases:
  pre_build:
    commands:
      - cd api
      - echo pwd
  build:
    commands:
      - npm install  
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - echo Pushing the Docker image...
  #     - echo docker push ${REPOSITORY_URI}/$IMAGE_REPO_NAME:$IMAGE_TAG
  #     - docker push ${REPOSITORY_URI}/$IMAGE_REPO_NAME:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  name: myname-$(AWS_REGION) 